source 'https://rubygems.org'

gem 'puppet-lint', '2.4.2'
gem 'puppet-lint-absolute_classname-check', '3.0.1'
gem 'puppet-lint-absolute_template_path', '1.0.1'
gem 'puppet-lint-classes_and_types_beginning_with_digits-check', '0.1.2'
gem 'puppet-lint-duplicate_class_parameters-check', '1.0.5'
gem 'puppet-lint-empty_string-check', '0.2.2'
gem 'puppet-lint-file_ensure-check', '0.3.1'
gem 'puppet-lint-leading_zero-check', '0.1.1'
gem 'puppet-lint-legacy_facts-check', '~> 1.0', '>= 1.0.4'
gem 'puppet-lint-manifest_whitespace-check', '~> 0.1.17'
gem 'puppet-lint-no_erb_template-check', '1.0.0'
gem 'puppet-lint-spaceship_operator_without_tag-check', '0.1.1'
gem 'puppet-lint-strict_indent-check', '2.0.8'
gem 'puppet-lint-trailing_comma-check', '0.4.2'
gem 'puppet-lint-trailing_newline-check', '1.1.0'
gem 'puppet-lint-undef_in_function-check', '0.2.1'
gem 'puppet-lint-unquoted_string-check', '2.1.0'
gem 'puppet-lint-variable_contains_upcase', '1.2.0'
gem 'puppet-lint-version_comparison-check', '0.2.1'
